apiVersion: v1
kind: Secret
metadata:
  name: mysql-developer
type: kubernetes.io/basic-auth
stringData:
  user: developer
  password: developer
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: cm9vdHBhc3N3b3Jk
